theme: jekyll-theme-modernist
plugins:
  "jekyll-github-metadata"
repository: keviland/keviland.github.io
"owner_name": "Kevin Landreneau", 
"owner_url": "https://github.com/keviland/keviland.github.io", 
"owner_gravatar_url": "https://github.com/keviland.png",
"repository_nwo": "keviland/keviland.github.io", 
"repository_name": "keviland Professional IT Services",
"url": "http://keviland.github.io/",

